import Head from 'next/head';
import { Inter } from 'next/font/google';

import { Auth } from '@supabase/auth-ui-react';
import { ThemeSupa } from '@supabase/auth-ui-shared';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';
import EditorForm from '@/components/EditorForm';
import Notes from '@/components/Notes';
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ['latin'] });

const DynamicEditorForm = dynamic(() => import('@/components/EditorForm'), {
  loading: () => <p>loading...</p>,
  ssr: false,
});

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`container`}>
        {!session ? (
          <Auth
            supabaseClient={supabase}
            appearance={{ theme: ThemeSupa }}
            theme="light"
            providers={['discord', 'github']}
          />
        ) : (
          <>
            <p>logged in.</p>
            <Notes />
            <DynamicEditorForm noteId={1} />
          </>
        )}
      </div>
    </>
  );
}
